#:kivy 2.3.0

<AdminEditServicesScreen>:
    name: "admin_edit_services"
    
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0.9, 0.85, 0.95, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Edit Services"
            font_size: '26sp'
            bold: True
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.5, "top": 0.95}
            size_hint: None, None
            size: dp(200), dp(50)

        Button:
            text: "<"
            size_hint: None, None
            size: dp(45), dp(45)
            color: 0, 0, 0, 1
            background_color: 0.45, 0.65, 0.85, 1   
            pos_hint: {"x": 0.03, "top": 0.97}
            on_release: app.root.current = "admin_profile"

        GridLayout:
            cols: 1
            spacing: dp(15)
            size_hint: None, None
            size: dp(250), dp(250)
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

            Button:
                text: "Add Service"
            Button:
                text: "Disability Type"
            Button:
                text: "Edit Staff"
            Button:
                text: "Delete Service"
                background_color: 0.9, 0.3, 0.3, 1
                color: 1, 1, 1, 1

          