#:kivy 2.3.0

<AdminProfileScreen>:
    name: "admin_profile"   
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0.9, 0.85, 0.95, 1  # Light purple
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Profile"
            font_size: '26sp'
            bold: True
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.5, "top": 0.95}
            size_hint: None, None
            size: dp(200), dp(50)

        GridLayout:
            cols: 1
            spacing: dp(15)
            size_hint: None, None
            size: dp(250), dp(400)
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

            Button:
                text: "Admin"
            Button:
                text: "Phone Number"
            Button:
                text: "Update Services"
                on_release: app.root,current = "admin_edit_services"
            Button:
                text: "Edit Organization"
                on_release: app.root.current = "admin_organization"
            Button:
                text: "Services Provided"
            Button:
                text: "Add Admin"
                background_color: 0.6, 0.4, 0.8, 1
                color: 1, 1, 1, 1
            Button:
                text: "Logout"
                background_color: 0.9, 0.3, 0.3, 1
                color: 1, 1, 1, 1
