#:kivy 2.3.0

<AdminHomeScreen>:
    name: "admin_home"

    FloatLayout:
        canvas.before:
            Color:
                rgba: 243/255, 234/255, 248/255, 1
            Rectangle:
                size: self.size
                pos: self.pos

        Label:
            text: "Admin Home"
            font_size: "24sp"
            bold: True
            pos_hint: {"center_x": 0.5, "top": 0.9}
            color: 0, 0, 0, 1

        Button:
            text: "Service Requested"
            size_hint: 0.8, None
            height: "50dp"
            pos_hint: {"center_x": 0.5, "top": 0.7}

        Button:
            text: "User Location"
            size_hint: 0.8, None
            height: "50dp"
            pos_hint: {"center_x": 0.5, "top": 0.6}
