#:kivy 2.3.0

<AdminSignupScreen>:
    name: "admin_signup"

    FloatLayout:
        canvas.before:
            Color:
                rgba: 243/255, 234/255, 248/255, 1
            Rectangle:
                size: self.size
                pos: self.pos

        Label:
            text: "WELCOME TO\nDIVYANG ASSISTANCE"
            halign: "center"
            bold: True
            font_size: "22sp"
            pos_hint: {"center_x": 0.5, "top": 0.9}
            color: 0, 0, 0, 1

        TextInput:
            id: full_name
            hint_text: "Full Name"
            size_hint: 0.8, None
            height: "45dp"
            pos_hint: {"center_x": 0.5, "top": 0.65}

        TextInput:
            hint_text: "Mobile Number"
            input_filter: "int"
            size_hint: 0.8, None
            height: "45dp"
            pos_hint: {"center_x": 0.5, "top": 0.55}

        TextInput:
            hint_text: "Organization Name"
            size_hint: 0.8, None
            height: "45dp"
            pos_hint: {"center_x": 0.5, "top": 0.45}

        Button:
            text: "Get Started"
            size_hint: 0.8, None
            height: "50dp"
            pos_hint: {"center_x": 0.5, "y": 0.1}
            on_release: root.submit_form()
