#:kivy 2.3.0

<ServiceScreen>:

    FloatLayout:

        canvas.before:
            Color:
                rgba: 1, 0.8, 0.9, 1
            Rectangle:
                size: self.size
                pos: self.pos


        Button:
            text: "< Back"
            size_hint: None, None
            size: dp(120), dp(45)
            pos_hint: {"x": 0.03, "top": 0.95}
            on_release: app.root.current = "map_home"


        Label:
            text: "Services"
            font_size: "22sp"
            bold: True
            pos_hint: {"center_x": .5, "top": .95}


        BoxLayout:
            orientation: "vertical"
            spacing: dp(12)
            size_hint: None, None
            size: dp(300), dp(330)
            pos_hint: {"center_x": .5, "center_y": .55}

            Button:
                text: "Wheelchair Allocation ♿"
                on_release: root.choose_service("Wheelchair")

            Button:
                text: "Guide Allocation 🧍"
                on_release: root.choose_service("Guide")

            Button:
                text: "Calling 📞"
                on_release: root.choose_service("Calling")

            Button:
                text: "Messaging 💬"
                on_release: root.choose_service("Messaging")

            Button:
                text: "Select This Service"
                background_color: 0.9, 0.3, 0.5, 1
                on_release: root.confirm_service()